Update types.go
aws/amazon-ec2-metadata-mock pull request #112
Opened 2020-12-23 16:00 UTC by julian3xl

these fields should accept null values

Issue #, if available:

aws-iam-authenticator throws a marshalling error because it expects nulls instead of empty strings on a few dynamic keys.

Description of changes:

To allow that, strings have to be changed by *strings to allow the null value on json marshalling.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-23 17:20 UTC, bwagner5 commented
Thanks for this! The tests are failing due to formatting. Can you run `make fmt` and update the PR. Everything else looks great!

2020-12-23 17:20 UTC, bwagner5 requested changes
Run `make fmt`

2021-01-05 15:59 UTC, merged

2021-01-05 20:17 UTC, julian3xl commented
Hi @bwagner5, apologies for my days off but you know, christmas. Thanks for leading the fmt fix and make it happen.-

2021-01-05 20:20 UTC, bwagner5 commented
No worries @julian3xl! Thanks again for the contribution! :)